import { Member, PracticeArea, Case, Review, SiteInfo, HeroSettings, StatsSettings } from '@/types';

// 사이트 기본 정보
export const SITE_INFO: SiteInfo = {
  name: '법무법인 성진',
  phone: '02-585-5200',
  fax: '02-585-5201',
  email: 'info@sungjinlaw.co.kr',
  address: '서울특별시 서초구 법원로4길 23, 성진빌딩 8층',
  addressDetail: '(서초동, 서울중앙지방법원 인근)',
  businessHours: '평일 09:00 - 18:00 | 야간·주말 상담 가능',
  kakaoLink: 'https://pf.kakao.com/_sungjinlaw',
};

// 히어로 설정
export const HERO_SETTINGS: HeroSettings = {
  title: '불합리한 결과에\n타협하지 않겠습니다',
  subtitle: '前 부장검사 출신 대표변호사가 직접 사건을 수임하고, 결과로 증명하는 법무법인 성진입니다.',
  imageUrl: '/images/hero-bg.jpg',
};

// 통계 설정
export const STATS_SETTINGS: StatsSettings = {
  consultations: 8500,
  cases: 2300,
  lawyers: 7,
  years: 18,
};

// 구성원 데이터
export const MEMBERS: Member[] = [
  {
    id: '1',
    name: '김성진',
    position: '대표변호사',
    photoUrl: '/images/members/member1.jpg',
    specialties: ['형사', '성범죄', '마약', '금융범죄'],
    education: '서울대학교 법학과 졸업\n사법연수원 제30기 수료\n서울대학교 법학대학원 형사법 석사',
    career: '前 서울중앙지방검찰청 부장검사\n前 대검찰청 강력부 검사\n前 법무법인 율촌 파트너변호사\n現 대한변호사협회 형사법연구회 부회장\n現 서울지방변호사회 형사전문변호사',
    achievements: '형사사건 무죄·무혐의 판결 120건 이상\n성범죄 무죄 판결 50건 이상\n마약사건 집행유예 100건 이상\n대법원 판례 변경 2건 기여',
    email: 'ks.kim@sungjinlaw.co.kr',
    displayOrder: 1,
    isActive: true,
  },
  {
    id: '2',
    name: '이정수',
    position: '파트너변호사',
    photoUrl: '/images/members/member2.jpg',
    specialties: ['이혼', '가사', '상속', '가정폭력'],
    education: '고려대학교 법학전문대학원 졸업 (수석)\n변호사시험 제5회 합격\n고려대학교 가족법연구 박사과정 수료',
    career: '前 서울가정법원 국선변호인 (3년)\n前 법률구조공단 가사전담 변호사\n前 여성가족부 법률자문위원\n現 대한가정법학회 이사\n現 서울가정법원 조정위원',
    achievements: '이혼 사건 조정·승소율 97%\n재산분할 극대화 성공 300건 이상\n양육권 분쟁 해결 150건 이상\n상속분쟁 해결 200건 이상',
    email: 'js.lee@sungjinlaw.co.kr',
    displayOrder: 2,
    isActive: true,
  },
  {
    id: '3',
    name: '박민영',
    position: '파트너변호사',
    photoUrl: '/images/members/member3.jpg',
    specialties: ['민사', '부동산', '건설', '계약분쟁'],
    education: '연세대학교 법학전문대학원 졸업\n변호사시험 제7회 합격\n연세대학교 부동산법 전문과정 수료',
    career: '前 삼성물산 사내변호사 (4년)\n前 법무법인 광장 부동산팀\n現 대한건설법학회 정회원\n現 서울특별시 건축분쟁조정위원\n現 한국부동산법학회 연구위원',
    achievements: '부동산 분쟁 승소율 94%\n건설분쟁 대형 사건 50건 이상 수행\n재개발·재건축 분쟁 전문\n임대차분쟁 해결 400건 이상',
    email: 'my.park@sungjinlaw.co.kr',
    displayOrder: 3,
    isActive: true,
  },
  {
    id: '4',
    name: '최현우',
    position: '파트너변호사',
    photoUrl: '/images/members/member4.jpg',
    specialties: ['교통사고', '음주운전', '산재', '보험'],
    education: '성균관대학교 법학전문대학원 졸업\n변호사시험 제10회 합격\n교통사고 손해사정사 자격',
    career: '前 교통사고전문 법률사무소 대표\n前 대한법률구조공단 교통사고 전담\n現 대한변협 교통법연구회 간사\n現 손해보험협회 자문위원',
    achievements: '교통사고 손해배상 800건 이상\n음주운전 구속영장 기각·집행유예 다수\n산업재해 보상 200건 이상\n보험사 대상 소송 승소율 91%',
    email: 'hw.choi@sungjinlaw.co.kr',
    displayOrder: 4,
    isActive: true,
  },
  {
    id: '5',
    name: '한서윤',
    position: '파트너변호사',
    photoUrl: '/images/members/member5.jpg',
    specialties: ['기업법무', '회생/파산', 'M&A', '스타트업'],
    education: '서울대학교 법학전문대학원 졸업\n변호사시험 제8회 합격\nUSC Law School LL.M.',
    career: '前 김앤장 법률사무소 기업팀 (3년)\n前 법원 회생사건 관리인 보조\n現 중소벤처기업부 법률자문위원\n現 서울회생법원 관리위원',
    achievements: '기업 회생 성공 30건 이상\nM&A 자문 총액 3,000억원 이상\n스타트업 법률자문 100사 이상\n기업분쟁 해결 200건 이상',
    email: 'sy.han@sungjinlaw.co.kr',
    displayOrder: 5,
    isActive: true,
  },
  {
    id: '6',
    name: '윤재호',
    position: '소속변호사',
    photoUrl: '/images/members/member6.jpg',
    specialties: ['학교폭력', '소년범', '청소년', '명예훼손'],
    education: '한양대학교 법학전문대학원 졸업\n변호사시험 제12회 합격\n범죄심리학 부전공',
    career: '前 서울가정법원 소년부 국선보조인\n前 청소년폭력예방재단 법률자문\n現 교육부 학교폭력 자문변호사\n現 서울시 청소년 권익옹호 위원',
    achievements: '학교폭력 사건 해결 300건 이상\n소년보호사건 불처분·보호관찰 획득 다수\n사이버 명예훼손 대응 100건 이상\n학교폭력 자치위원회 대리 승률 89%',
    email: 'jh.yoon@sungjinlaw.co.kr',
    displayOrder: 6,
    isActive: true,
  },
  {
    id: '7',
    name: '정다은',
    position: '소속변호사',
    photoUrl: '/images/members/member7.jpg',
    specialties: ['행정소송', '조세', '인허가', '공정거래'],
    education: '이화여자대학교 법학전문대학원 졸업\n변호사시험 제11회 합격\n세무사 자격 보유',
    career: '前 국세청 조세심판원 조사관\n前 법무법인 태평양 조세팀\n現 한국세법학회 연구위원\n現 서울지방국세청 과세적부심 위원',
    achievements: '조세불복 인용률 78% (업계 평균 30%)\n행정소송 승소 80건 이상\n세무조사 대응 50건 이상\n과징금 감면·취소 다수',
    email: 'de.jung@sungjinlaw.co.kr',
    displayOrder: 7,
    isActive: true,
  },
];

// 업무분야 데이터
export const PRACTICE_AREAS: PracticeArea[] = [
  {
    id: '1',
    name: '형사사건',
    slug: 'criminal',
    icon: 'Gavel',
    description: '성범죄, 폭력, 사기, 마약, 금융범죄 등 모든 형사사건 전문',
    content: '前 부장검사 출신 대표변호사가 수사 초기 단계부터 직접 개입합니다. 경찰 조사 동행부터 검찰 대응, 법정 변론까지 원스톱 법률서비스를 제공합니다. 불합리한 기소와 과도한 형량에 타협하지 않고, 의뢰인의 권리를 끝까지 지켜드립니다. 24시간 긴급 대응 체계를 갖추고 있어 구속영장 발부 시에도 즉시 대응이 가능합니다.',
    displayOrder: 1,
    isActive: true,
  },
  {
    id: '2',
    name: '이혼/가사',
    slug: 'family',
    icon: 'Heart',
    description: '이혼, 양육권, 재산분할, 상속, 가정폭력 전문',
    content: '가족 간의 갈등은 법적 문제이자 감정의 문제입니다. 법무법인 성진은 의뢰인의 감정에 공감하면서도, 냉정한 법적 분석으로 최선의 결과를 이끌어냅니다. 협의이혼 협상부터 재판이혼, 양육권·면접교섭권 분쟁, 재산분할 극대화, 위자료 청구까지 가사 전 분야를 전담합니다. 가정폭력 피해자 긴급보호 및 접근금지 가처분도 신속하게 처리합니다.',
    displayOrder: 2,
    isActive: true,
  },
  {
    id: '3',
    name: '민사/부동산',
    slug: 'civil',
    icon: 'Building2',
    description: '부동산분쟁, 손해배상, 임대차, 건설분쟁, 채권추심',
    content: '삼성물산 사내변호사 출신 파트너변호사가 이끄는 부동산·건설 전문팀입니다. 매매·임대차 분쟁, 건축 하자 소송, 재개발·재건축 조합원 분쟁, 명도소송 등 부동산 전 분야를 다룹니다. 손해배상 청구, 채권추심, 계약서 검토 등 민사 전반의 법률서비스도 제공합니다. 대형 건설사 및 시행사 자문 경험을 바탕으로, 복잡한 건설분쟁도 해결합니다.',
    displayOrder: 3,
    isActive: true,
  },
  {
    id: '4',
    name: '기업법무',
    slug: 'corporate',
    icon: 'Briefcase',
    description: '기업자문, M&A, 회생/파산, 스타트업, 계약서 검토',
    content: '김앤장 출신 파트너변호사가 이끄는 기업법무팀입니다. 스타트업 설립 자문부터 대기업 M&A, 기업 회생까지 기업의 생애주기 전반을 지원합니다. 주주간 계약, 투자계약, 합작투자, 지식재산권 분쟁 등 기업 경영에 필요한 모든 법률 서비스를 제공합니다. 위기 상황의 기업 회생 절차도 성공적으로 이끌어온 검증된 역량을 보유하고 있습니다.',
    displayOrder: 4,
    isActive: true,
  },
  {
    id: '5',
    name: '교통/산재',
    slug: 'traffic',
    icon: 'Car',
    description: '교통사고, 음주운전, 산업재해, 보험분쟁',
    content: '교통사고 손해사정사 자격을 겸비한 전문변호사가 담당합니다. 교통사고 피해보상 극대화, 음주·무면허 운전 형사 변론, 전동킥보드·자전거 사고 대응, 보험사 분쟁 등을 전문적으로 처리합니다. 산업재해 피해근로자의 산재보험급여 청구, 사업주 대상 손해배상 소송도 풍부한 경험으로 해결합니다. 사고 현장 조사부터 보험금 수령까지 전 과정을 관리합니다.',
    displayOrder: 5,
    isActive: true,
  },
  {
    id: '6',
    name: '학교폭력/청소년',
    slug: 'school-violence',
    icon: 'Shield',
    description: '학교폭력, 소년사건, 사이버 불링, 청소년 인권',
    content: '교육부 학교폭력 자문변호사가 직접 대응합니다. 학교폭력 자치위원회 대리, 피해학생 보호·치유 지원, 가해학생 조치 감경, 학폭 기록 삭제 등을 전문으로 합니다. 사이버 불링, SNS 명예훼손 등 디지털 환경의 학교폭력에도 전문적으로 대응합니다. 소년보호사건에서는 불처분·보호관찰 획득을 목표로, 청소년의 미래를 지키기 위해 최선을 다합니다.',
    displayOrder: 6,
    isActive: true,
  },
  {
    id: '7',
    name: '행정/조세',
    slug: 'administrative',
    icon: 'FileText',
    description: '행정소송, 조세불복, 세무조사, 인허가, 공정거래',
    content: '국세청 조세심판원 출신 변호사와 세무사 자격을 겸비한 전문가가 담당합니다. 세무조사 대응, 과세처분 불복, 조세심판, 행정소송까지 원스톱 서비스를 제공합니다. 행정처분 취소·무효소송, 인허가 취득·갱신, 영업정지 처분 대응, 공정거래 과징금 감면 등 행정법 전 분야를 다룹니다. 업계 평균 30%인 조세불복 인용률 대비, 성진의 인용률은 78%입니다.',
    displayOrder: 7,
    isActive: true,
  },
];

// 성공사례 데이터
export const CASES: Case[] = [
  {
    id: '1',
    title: '성범죄 혐의 무죄 판결 — 허위고소 입증',
    areaId: '1',
    areaName: '형사사건',
    memberId: '1',
    memberName: '김성진',
    resultSummary: '무죄 판결 확정',
    overview: '의뢰인은 전 교제상대의 허위 고소로 성폭력 혐의를 받게 되었습니다. 이미 경찰 조사가 진행 중인 상태에서 내방하셨으며, 구속수사 가능성이 높은 상황이었습니다. 수사 초기 단계부터 개입하여 CCTV 분석, 카카오톡 대화 내역 복원, 목격자 확보 등을 통해 고소인 진술의 모순점을 체계적으로 입증하였습니다.',
    result: '검찰 단계에서 불기소 의견을 제시하였으나 기소가 진행되어, 1심에서 무죄 판결을 받았습니다. 검찰이 항소를 포기하여 무죄가 확정되었고, 이후 무고죄 반소를 제기하여 고소인에 대한 처벌도 이끌어냈습니다.',
    thumbnailUrl: '/images/cases/case1.jpg',
    isPublished: true,
    createdAt: '2024-01-15',
  },
  {
    id: '2',
    title: '20년 혼인 이혼소송 — 재산분할 70% 인정',
    areaId: '2',
    areaName: '이혼/가사',
    memberId: '2',
    memberName: '이정수',
    resultSummary: '재산분할 70% + 위자료 5천만원',
    overview: '20년간 전업주부로 가정을 지켜온 의뢰인은 배우자의 외도로 이혼을 결심하셨습니다. 상대방은 고소득 전문직으로, 재산 대부분이 본인 명의였습니다. 의뢰인의 내조 및 가사노동 기여도를 구체적으로 입증하기 위해 가계부, 자녀 양육 기록, 배우자의 업무 시간 분석 등 다각적인 증거를 확보하였습니다.',
    result: '법원은 의뢰인의 기여도를 인정하여 통상 50%인 재산분할 비율을 70%까지 인정하였습니다. 이에 더해 배우자의 유책사유(외도)를 입증하여 위자료 5천만원을 추가로 받아냈습니다. 자녀 양육권도 의뢰인에게 인정되었습니다.',
    thumbnailUrl: '/images/cases/case2.jpg',
    isPublished: true,
    createdAt: '2024-02-20',
  },
  {
    id: '3',
    title: '상가 명도소송 — 4개월 만에 강제집행 완료',
    areaId: '3',
    areaName: '민사/부동산',
    memberId: '3',
    memberName: '박민영',
    resultSummary: '전부 승소 + 강제집행 완료',
    overview: '서초구 소재 상가건물의 임차인이 월세를 6개월 이상 연체하고 연락이 두절된 상황이었습니다. 건물 내부에는 임차인의 물건이 방치되어 있어 임의 처분도 불가능한 상태였습니다. 신속한 소송 진행과 동시에 보전처분(가압류)을 통해 임차인의 재산도 확보하였습니다.',
    result: '소송 제기 후 4개월 만에 명도 판결을 받고, 즉시 강제집행을 완료하였습니다. 연체된 월세 및 지연손해금 전액도 회수에 성공하였습니다. 의뢰인은 신속하게 새로운 임차인을 유치할 수 있었습니다.',
    thumbnailUrl: '/images/cases/case3.jpg',
    isPublished: true,
    createdAt: '2024-03-10',
  },
  {
    id: '4',
    title: '음주운전 면허취소 수준 — 집행유예 획득',
    areaId: '5',
    areaName: '교통/산재',
    memberId: '4',
    memberName: '최현우',
    resultSummary: '집행유예 선고',
    overview: '혈중알코올농도 0.15%로 적발된 의뢰인은 직장인으로서 실형 선고 시 생계가 위협받는 상황이었습니다. 이전에 벌금 전력이 있어 실형 가능성이 높았습니다. 의뢰인의 진심어린 반성과 구체적인 재범방지 대책(음주운전 예방교육 이수, 차량 처분 등)을 법원에 설득력 있게 제시하였습니다.',
    result: '징역 1년에 집행유예 2년을 선고받아 실형을 면하였습니다. 사회봉사 200시간이 부과되었으나, 직장을 유지하며 생활할 수 있게 되었습니다.',
    thumbnailUrl: '/images/cases/case4.jpg',
    isPublished: true,
    createdAt: '2024-04-05',
  },
  {
    id: '5',
    title: '학교폭력 피해학생 보호 — 가해학생 전학 조치',
    areaId: '6',
    areaName: '학교폭력/청소년',
    memberId: '6',
    memberName: '윤재호',
    resultSummary: '가해학생 전학 + 피해보상',
    overview: '중학교 2학년 학생이 같은 반 학생들로부터 지속적인 집단 괴롭힘을 당하고 있었습니다. 학교 측은 소극적으로 대응하고 있었고, 피해학생은 등교를 거부하는 상태였습니다. 피해학생의 심리상담 기록, SNS 괴롭힘 증거, 목격자 진술 등을 체계적으로 수집하여 학교폭력 자치위원회에 제출하였습니다.',
    result: '자치위원회에서 가해학생들에게 강제전학 조치가 내려졌으며, 가해학생 부모로부터 치료비 및 위자료로 총 2,000만원의 합의금을 받아냈습니다. 피해학생은 현재 정상적으로 학교생활을 하고 있습니다.',
    thumbnailUrl: '/images/cases/case5.jpg',
    isPublished: true,
    createdAt: '2024-05-20',
  },
  {
    id: '6',
    title: '기업 회생 성공 — 부채 80% 탕감',
    areaId: '4',
    areaName: '기업법무',
    memberId: '5',
    memberName: '한서윤',
    resultSummary: '회생인가 + 부채 80% 탕감',
    overview: '매출 50억 규모의 IT 기업이 코로나 이후 매출 급감으로 부채가 30억원에 달하는 상황이었습니다. 대표이사는 파산을 고려하고 있었으나, 핵심 기술력과 거래처가 유지되고 있어 회생 가능성이 있었습니다. 법원에 회생 신청을 하고, 채권자들과의 협상을 병행하였습니다.',
    result: '법원으로부터 회생계획 인가를 받아 부채의 80%를 탕감받았습니다. 나머지 20%는 5년 분할 상환으로 결정되었고, 현재 기업은 흑자 전환에 성공하여 정상 운영 중입니다.',
    thumbnailUrl: '/images/cases/case6.jpg',
    isPublished: true,
    createdAt: '2024-06-15',
  },
  {
    id: '7',
    title: '과징금 5억원 취소소송 — 전액 취소',
    areaId: '7',
    areaName: '행정/조세',
    memberId: '7',
    memberName: '정다은',
    resultSummary: '과징금 5억원 전액 취소',
    overview: '프랜차이즈 기업이 공정거래위원회로부터 불공정거래 혐의로 과징금 5억원을 부과받았습니다. 회사 측은 정당한 영업활동이었다고 주장하였으나, 행정처분이 확정되면 사업 존속이 어려운 상황이었습니다. 공정거래법 위반 요건을 면밀히 분석하고, 처분의 절차적 하자를 발견하였습니다.',
    result: '행정소송을 통해 과징금 5억원 전액 취소 판결을 받았습니다. 재판부는 공정위의 조사 절차에 하자가 있었고, 위반 사실 인정에 증거가 부족하다고 판단하였습니다.',
    thumbnailUrl: '/images/cases/case7.jpg',
    isPublished: true,
    createdAt: '2024-07-10',
  },
  {
    id: '8',
    title: '마약 투약 혐의 — 기소유예 처분',
    areaId: '1',
    areaName: '형사사건',
    memberId: '1',
    memberName: '김성진',
    resultSummary: '기소유예 (전과기록 없음)',
    overview: '20대 대학생인 의뢰인이 클럽에서 지인의 권유로 대마를 흡연하여 마약류관리법 위반 혐의를 받게 되었습니다. 초범이었으나, 마약 사건은 실형이 선고되는 경우가 많아 매우 불안한 상태였습니다. 의뢰인의 반성 의지와 재범방지 노력(재활프로그램 참여, 교우관계 정리)을 검찰에 적극 어필하였습니다.',
    result: '검찰에서 기소유예 처분을 받아 전과기록이 남지 않게 되었습니다. 의뢰인은 현재 정상적으로 대학 생활을 이어가고 있습니다.',
    thumbnailUrl: '/images/cases/case8.jpg',
    isPublished: true,
    createdAt: '2024-08-01',
  },
];

// 후기 데이터
export const REVIEWS: Review[] = [
  {
    id: '1',
    authorName: '김*호',
    rating: 5,
    content: '정말 막막했던 상황에서 김성진 변호사님을 만나 무죄 판결을 받았습니다. 경찰 조사부터 법정까지 모든 과정에서 흔들림 없이 저를 지켜주셨습니다. 처음 상담 때부터 사건의 핵심을 정확히 짚어주셔서 신뢰가 갔고, 결과로 그 믿음을 증명해주셨습니다. 인생의 은인입니다.',
    areaId: '1',
    areaName: '형사사건',
    memberId: '1',
    memberName: '김성진',
    isPublished: true,
    createdAt: '2024-01-20',
  },
  {
    id: '2',
    authorName: '이*영',
    rating: 5,
    content: '20년간의 결혼생활을 정리하면서 감정적으로 많이 힘들었는데, 이정수 변호사님 덕분에 법적으로 최선의 결과를 얻을 수 있었습니다. 항상 제 입장에서 생각해주시고, 복잡한 법률 내용도 쉽게 설명해주셔서 큰 위로가 되었습니다. 재산분할도 기대 이상이었습니다.',
    areaId: '2',
    areaName: '이혼/가사',
    memberId: '2',
    memberName: '이정수',
    isPublished: true,
    createdAt: '2024-02-25',
  },
  {
    id: '3',
    authorName: '박*수',
    rating: 5,
    content: '임차인 때문에 1년 넘게 고생했는데, 박민영 변호사님께서 4개월 만에 깔끔하게 해결해주셨습니다. 소송 진행 상황을 매주 카톡으로 알려주셔서 불안하지 않았고, 밀린 월세까지 전액 회수해주셨습니다. 비용 대비 결과가 정말 만족스럽습니다.',
    areaId: '3',
    areaName: '민사/부동산',
    memberId: '3',
    memberName: '박민영',
    isPublished: true,
    createdAt: '2024-03-15',
  },
  {
    id: '4',
    authorName: '최*민',
    rating: 5,
    content: '한순간의 실수로 음주운전을 해서 앞길이 막막했습니다. 다른 곳에서는 실형 가능성이 높다고 했는데, 최현우 변호사님이 집행유예를 받아주셔서 직장도 유지할 수 있었습니다. 변호사님의 꼼꼼한 준비와 법정에서의 설득력 있는 변론 덕분입니다.',
    areaId: '5',
    areaName: '교통/산재',
    memberId: '4',
    memberName: '최현우',
    isPublished: true,
    createdAt: '2024-04-10',
  },
  {
    id: '5',
    authorName: '정*희',
    rating: 5,
    content: '아이가 학교에서 왕따를 당하고 있었는데, 학교에서는 제대로 대처를 안 해주더라구요. 윤재호 변호사님께 의뢰 후 자치위원회에서 가해학생 전학 조치를 받아내고, 합의금도 받았습니다. 아이 심리상담까지 신경 써주셔서 정말 감사합니다.',
    areaId: '6',
    areaName: '학교폭력/청소년',
    memberId: '6',
    memberName: '윤재호',
    isPublished: true,
    createdAt: '2024-05-25',
  },
  {
    id: '6',
    authorName: '송*준',
    rating: 5,
    content: '회사가 부도 직전이었는데, 한서윤 변호사님의 기업회생 전문성 덕분에 회사를 살릴 수 있었습니다. 채권자 협상도 능숙하게 진행해주시고, 법원 심리에서도 명확하게 설명해주셨습니다. 지금은 회사가 흑자 전환되어 정상 운영 중입니다.',
    areaId: '4',
    areaName: '기업법무',
    memberId: '5',
    memberName: '한서윤',
    isPublished: true,
    createdAt: '2024-06-20',
  },
  {
    id: '7',
    authorName: '강*미',
    rating: 5,
    content: '국세청에서 세무조사를 받고 과징금이 나왔을 때 정말 하늘이 무너지는 것 같았습니다. 정다은 변호사님이 꼼꼼하게 분석해서 행정소송으로 과징금 전액 취소를 받아주셨습니다. 세무사 자격까지 가지고 계셔서 세금 문제를 정확히 이해하시더라구요.',
    areaId: '7',
    areaName: '행정/조세',
    memberId: '7',
    memberName: '정다은',
    isPublished: true,
    createdAt: '2024-07-15',
  },
  {
    id: '8',
    authorName: '오*석',
    rating: 5,
    content: '다른 법무법인 두 곳에서 어렵다고 했던 사건인데, 법무법인 성진에서 결국 해결해주셨습니다. 김성진 대표변호사님의 경험과 전문성이 다른 곳과는 차원이 다르다는 걸 느꼈습니다. 포기하지 않고 끝까지 함께해주셔서 감사합니다.',
    areaId: '1',
    areaName: '형사사건',
    memberId: '1',
    memberName: '김성진',
    isPublished: true,
    createdAt: '2024-08-05',
  },
];

// 네비게이션 메뉴
export const NAV_ITEMS = [
  { label: '법인 소개', href: '/about' },
  { label: '구성원', href: '/members' },
  { label: '업무분야', href: '/practice' },
  { label: '성공사례', href: '/cases' },
  { label: '의뢰인 후기', href: '/reviews' },
  { label: '오시는 길', href: '/location' },
];
