import { Member, PracticeArea, Case, Review, SiteInfo, HeroSettings, StatsSettings } from '@/types';

// 사이트 기본 정보
export const SITE_INFO: SiteInfo = {
  name: '법무법인 성진',
  phone: '02-1234-5678',
  fax: '02-1234-5679',
  email: 'contact@sungjinlaw.com',
  address: '서울특별시 서초구 서초대로 000, 법조빌딩 10층',
  addressDetail: '(서초동, 법조빌딩)',
  businessHours: '평일 09:00 - 18:00',
  kakaoLink: 'https://pf.kakao.com/_example',
};

// 히어로 설정
export const HERO_SETTINGS: HeroSettings = {
  title: '당신의 권리를\n끝까지 지켜드립니다',
  subtitle: '30년 경력의 법률 전문가들이 최선의 결과를 약속합니다',
  imageUrl: '/images/hero-bg.jpg',
};

// 통계 설정
export const STATS_SETTINGS: StatsSettings = {
  consultations: 5000,
  cases: 1200,
  lawyers: 5,
  years: 15,
};

// 구성원 Mock 데이터
export const MEMBERS: Member[] = [
  {
    id: '1',
    name: '김성진',
    position: '대표변호사',
    photoUrl: '/images/members/member1.jpg',
    specialties: ['형사', '성범죄', '마약'],
    education: '서울대학교 법학과 졸업\n사법연수원 제30기 수료',
    career: '前 서울중앙지방검찰청 검사\n前 법무법인 율촌 파트너변호사\n現 대한변호사협회 형사법연구회 위원',
    achievements: '성범죄 무죄 판결 50건 이상\n마약사건 집행유예 100건 이상',
    displayOrder: 1,
    isActive: true,
  },
  {
    id: '2',
    name: '이정수',
    position: '파트너변호사',
    photoUrl: '/images/members/member2.jpg',
    specialties: ['이혼', '가사', '상속'],
    education: '고려대학교 법학전문대학원 졸업\n변호사시험 제5회 합격',
    career: '前 서울가정법원 국선변호인\n前 법률구조공단 가사전담\n現 대한가정법학회 정회원',
    achievements: '이혼 조정 성공률 95%\n상속분쟁 해결 200건 이상',
    displayOrder: 2,
    isActive: true,
  },
  {
    id: '3',
    name: '박민영',
    position: '파트너변호사',
    photoUrl: '/images/members/member3.jpg',
    specialties: ['민사', '부동산', '계약'],
    education: '연세대학교 법학전문대학원 졸업\n변호사시험 제7회 합격',
    career: '前 대형 건설사 사내변호사\n前 법무법인 광장\n現 대한건설법학회 회원',
    achievements: '부동산 분쟁 승소율 92%\n대형 건설분쟁 다수 수행',
    displayOrder: 3,
    isActive: true,
  },
  {
    id: '4',
    name: '최현우',
    position: '소속변호사',
    photoUrl: '/images/members/member4.jpg',
    specialties: ['교통사고', '음주운전', '산재'],
    education: '성균관대학교 법학전문대학원 졸업\n변호사시험 제10회 합격',
    career: '前 교통사고전문 법률사무소\n現 대한변협 교통법연구회',
    achievements: '교통사고 손해배상 500건 이상\n음주운전 사건 무혐의/집행유예 다수',
    displayOrder: 4,
    isActive: true,
  },
];

// 업무분야 Mock 데이터
export const PRACTICE_AREAS: PracticeArea[] = [
  {
    id: '1',
    name: '형사사건',
    slug: 'criminal',
    icon: 'Gavel',
    description: '성범죄, 폭력, 사기, 마약 등 모든 형사사건',
    content: '30년 경력의 前 검사 출신 변호사가 직접 상담하고 변론합니다. 수사 초기 단계부터 재판까지 원스톱 법률서비스를 제공합니다.',
    displayOrder: 1,
    isActive: true,
  },
  {
    id: '2',
    name: '이혼/가사',
    slug: 'family',
    icon: 'Heart',
    description: '이혼, 양육권, 재산분할, 상속 분쟁',
    content: '가족 간의 갈등을 법적으로 원만하게 해결해드립니다. 협의이혼부터 재판이혼까지, 의뢰인의 권익을 최우선으로 합니다.',
    displayOrder: 2,
    isActive: true,
  },
  {
    id: '3',
    name: '민사/부동산',
    slug: 'civil',
    icon: 'Building2',
    description: '손해배상, 부동산 분쟁, 임대차, 채권추심',
    content: '계약 분쟁, 부동산 분쟁, 손해배상 청구 등 민사 전반에 걸친 법률서비스를 제공합니다.',
    displayOrder: 3,
    isActive: true,
  },
  {
    id: '4',
    name: '기업법무',
    slug: 'corporate',
    icon: 'Briefcase',
    description: '기업 자문, 계약서 검토, 회생/파산',
    content: '중소기업부터 대기업까지, 기업 운영에 필요한 모든 법률 자문을 제공합니다.',
    displayOrder: 4,
    isActive: true,
  },
  {
    id: '5',
    name: '교통/산재',
    slug: 'traffic',
    icon: 'Car',
    description: '교통사고, 음주운전, 산업재해',
    content: '교통사고 피해자 구제 및 가해자 변론, 산업재해 보상 청구까지 전문적으로 처리합니다.',
    displayOrder: 5,
    isActive: true,
  },
  {
    id: '6',
    name: '행정/조세',
    slug: 'administrative',
    icon: 'FileText',
    description: '행정소송, 조세불복, 인허가',
    content: '행정처분에 대한 불복, 세금 관련 분쟁을 전문적으로 처리합니다.',
    displayOrder: 6,
    isActive: true,
  },
];

// 성공사례 Mock 데이터
export const CASES: Case[] = [
  {
    id: '1',
    title: '성범죄 혐의 무죄 판결',
    areaId: '1',
    areaName: '형사사건',
    memberId: '1',
    memberName: '김성진',
    resultSummary: '무죄 판결',
    overview: '의뢰인은 지인의 허위 고소로 성범죄 혐의를 받게 되었습니다. 수사 초기 단계부터 함께하여 CCTV 분석, 알리바이 입증 등을 통해 혐의 사실이 없음을 증명하였습니다.',
    result: '1심에서 무죄 판결을 받았으며, 검찰 항소 없이 확정되었습니다.',
    thumbnailUrl: '/images/cases/case1.jpg',
    isPublished: true,
    createdAt: '2024-01-15',
  },
  {
    id: '2',
    title: '이혼 소송 재산분할 극대화',
    areaId: '2',
    areaName: '이혼/가사',
    memberId: '2',
    memberName: '이정수',
    resultSummary: '재산분할 70% 인정',
    overview: '20년간 전업주부로 가정을 지켜온 의뢰인의 기여도를 입증하여 재산분할 비율을 극대화하였습니다.',
    result: '통상 50%인 재산분할 비율을 70%까지 인정받았으며, 위자료 5천만원을 추가로 받아냈습니다.',
    thumbnailUrl: '/images/cases/case2.jpg',
    isPublished: true,
    createdAt: '2024-02-20',
  },
  {
    id: '3',
    title: '건물 명도소송 승소',
    areaId: '3',
    areaName: '민사/부동산',
    memberId: '3',
    memberName: '박민영',
    resultSummary: '전부 승소',
    overview: '임차인이 월세를 6개월 이상 연체하고 연락이 두절된 상황에서, 신속한 명도소송을 진행하여 건물을 회복하였습니다.',
    result: '소송 제기 4개월 만에 명도 판결을 받고, 강제집행까지 완료하였습니다.',
    thumbnailUrl: '/images/cases/case3.jpg',
    isPublished: true,
    createdAt: '2024-03-10',
  },
  {
    id: '4',
    title: '음주운전 집행유예 획득',
    areaId: '5',
    areaName: '교통/산재',
    memberId: '4',
    memberName: '최현우',
    resultSummary: '집행유예',
    overview: '혈중알코올농도 0.15%로 적발된 의뢰인을 위해 진심어린 반성과 재범방지 대책을 법원에 설득하였습니다.',
    result: '징역 1년에 집행유예 2년을 선고받아 실형을 면하였습니다.',
    thumbnailUrl: '/images/cases/case4.jpg',
    isPublished: true,
    createdAt: '2024-04-05',
  },
];

// 후기 Mock 데이터
export const REVIEWS: Review[] = [
  {
    id: '1',
    authorName: '김*호',
    rating: 5,
    content: '정말 막막했던 상황에서 김성진 변호사님을 만나 무죄 판결을 받았습니다. 처음부터 끝까지 자세하게 설명해주시고, 항상 의뢰인 입장에서 생각해주셔서 정말 감사드립니다.',
    areaId: '1',
    areaName: '형사사건',
    memberId: '1',
    memberName: '김성진',
    isPublished: true,
    createdAt: '2024-01-20',
  },
  {
    id: '2',
    authorName: '이*영',
    rating: 5,
    content: '20년간의 결혼생활을 정리하면서 많이 힘들었는데, 이정수 변호사님 덕분에 최선의 결과를 얻을 수 있었습니다. 친절하게 상담해주셔서 마음의 위로도 받았습니다.',
    areaId: '2',
    areaName: '이혼/가사',
    memberId: '2',
    memberName: '이정수',
    isPublished: true,
    createdAt: '2024-02-25',
  },
  {
    id: '3',
    authorName: '박*수',
    rating: 5,
    content: '임차인 때문에 1년 넘게 고생했는데, 박민영 변호사님께서 빠르고 정확하게 처리해주셨습니다. 비용 대비 결과가 매우 만족스럽습니다.',
    areaId: '3',
    areaName: '민사/부동산',
    memberId: '3',
    memberName: '박민영',
    isPublished: true,
    createdAt: '2024-03-15',
  },
  {
    id: '4',
    authorName: '최*민',
    rating: 5,
    content: '실수로 음주운전을 해서 앞길이 막막했는데, 집행유예를 받아 직장을 유지할 수 있었습니다. 최현우 변호사님 정말 감사합니다.',
    areaId: '5',
    areaName: '교통/산재',
    memberId: '4',
    memberName: '최현우',
    isPublished: true,
    createdAt: '2024-04-10',
  },
  {
    id: '5',
    authorName: '정*희',
    rating: 5,
    content: '다른 곳에서는 어렵다고 했던 사건인데, 법무법인 성진에서 해결해주셨습니다. 포기하지 않고 끝까지 함께해주셔서 감사합니다.',
    areaId: '1',
    areaName: '형사사건',
    memberId: '1',
    memberName: '김성진',
    isPublished: true,
    createdAt: '2024-05-01',
  },
];

// 네비게이션 메뉴
export const NAV_ITEMS = [
  { label: '법인 소개', href: '/about' },
  { label: '구성원', href: '/members' },
  { label: '업무분야', href: '/practice' },
  { label: '성공사례', href: '/cases' },
  { label: '의뢰인 후기', href: '/reviews' },
  { label: '오시는 길', href: '/location' },
];
